# Generated by Django 4.2.1 on 2023-05-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_name", models.CharField(max_length=100)),
                ("mgt_intf", models.CharField(blank=True, max_length=200)),
                ("mgt_ip", models.CharField(blank=True, max_length=200)),
                ("hwsku", models.CharField(blank=True, max_length=200)),
                ("mac", models.CharField(max_length=200)),
                ("platform", models.CharField(blank=True, max_length=200)),
                ("type", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name_plural": "Devices",
            },
        ),
    ]
