# Generated by Django 4.2.1 on 2023-05-05 03:17

from django.db import migrations

def create_data(apps, schema_editor):
    Device = apps.get_model('device', 'Device')
    Device(img_name="Joe Silver", mgt_intf="joe@email.com", mgt_ip="22342342", hwsku="00000000").save()


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
