import React, { useEffect, useMemo, useState } from "react";
import { Chart } from "react-google-charts";
import "ag-grid-community/styles/ag-grid.css";
import "ag-grid-community/styles/ag-theme-alpine.css";
import { AgGridReact } from "ag-grid-react";
import SigmaGraph from "./../graphsNcharts/sigmaGraph/sigmaGraph";

const ErrorPage = () => {
    // const data = {
    //     cols: [
    //         {
    //             label: "Lag Name",
    //             type: "string",
    //         },
    //         {
    //             label: "Active",
    //             type: "boolean",
    //         },
    //         {
    //             label: "Admin Status",
    //             type: "string",
    //         },
    //         {
    //             label: "MTU",
    //             type: "number",
    //         },
    //         {
    //             label: "Name",
    //             type: "string",
    //         },
    //         {
    //             label: "Fallback Operational",
    //             type: "boolean",
    //         },
    //         {
    //             label: "Operational Status",
    //             type: "string",
    //         },
    //         {
    //             label: "Speed",
    //             type: "string",
    //         },
    //         {
    //             label: "Operational Status Reason",
    //             type: "string",
    //         },
    //         {
    //             label: "ID",
    //             type: "number",
    //         },
    //     ],
    //     rows: [
    //         {
    //             c: [
    //                 {
    //                     v: "PortChannel102",
    //                 },
    //                 {
    //                     v: true,
    //                 },
    //                 {
    //                     v: "up",
    //                 },
    //                 {
    //                     v: 9100,
    //                 },
    //                 {
    //                     v: "lacp",
    //                 },
    //                 {
    //                     v: true,
    //                 },
    //                 {
    //                     v: "down",
    //                 },
    //                 {
    //                     v: "0",
    //                 },
    //                 {
    //                     v: "LACP_FAIL",
    //                 },
    //                 {
    //                     v: 157,
    //                 },
    //             ],
    //         },
    //         {
    //             c: [
    //                 {
    //                     v: "PortChannel101",
    //                 },
    //                 {
    //                     v: true,
    //                 },
    //                 {
    //                     v: "up",
    //                 },
    //                 {
    //                     v: 9100,
    //                 },
    //                 {
    //                     v: "lacp",
    //                 },
    //                 {
    //                     v: true,
    //                 },
    //                 {
    //                     v: "down",
    //                 },
    //                 {
    //                     v: "0",
    //                 },
    //                 {
    //                     v: "ALL_LINKS_DOWN",
    //                 },
    //                 {
    //                     v: 74,
    //                 },
    //             ],
    //         },
    //     ],
    // };

    // const data = {
    //     content: [
    //         {
    //             name: "Ethernet56",
    //             enabled: true,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_100GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 51,
    //         },
    //         {
    //             name: "Management0",
    //             enabled: true,
    //             mtu: 1500,
    //             fec: null,
    //             speed: "SPEED_1GB",
    //             oper_sts: "UP",
    //             admin_sts: "UP",
    //             description: "Management0",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:00",
    //             id: 58,
    //         },
    //         {
    //             name: "Ethernet76",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_100GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "UP",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 57,
    //         },
    //         {
    //             name: "Ethernet72",
    //             enabled: true,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_100GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "UP",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 56,
    //         },
    //         {
    //             name: "Ethernet68",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_100GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 55,
    //         },
    //         {
    //             name: "Ethernet64",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_100GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 54,
    //         },
    //         {
    //             name: "Ethernet60",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_100GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 53,
    //         },
    //         {
    //             name: "Ethernet0",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_10GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 1,
    //         },
    //         {
    //             name: "Ethernet1",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_10GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 2,
    //         },
    //         {
    //             name: "Ethernet2",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_10GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 3,
    //         },
    //         {
    //             name: "Ethernet3",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_10GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 4,
    //         },
    //         {
    //             name: "Ethernet4",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 5,
    //         },
    //         {
    //             name: "Ethernet5",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 6,
    //         },
    //         {
    //             name: "Ethernet6",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 7,
    //         },
    //         {
    //             name: "Ethernet7",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 8,
    //         },
    //         {
    //             name: "Ethernet8",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 9,
    //         },
    //         {
    //             name: "Ethernet9",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 10,
    //         },
    //         {
    //             name: "Ethernet10",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 11,
    //         },
    //         {
    //             name: "Ethernet11",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 12,
    //         },
    //         {
    //             name: "Ethernet12",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 13,
    //         },
    //         {
    //             name: "Ethernet13",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 14,
    //         },
    //         {
    //             name: "Ethernet14",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 15,
    //         },
    //         {
    //             name: "Ethernet15",
    //             enabled: true,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "UP",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 16,
    //         },
    //         {
    //             name: "Ethernet16",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 17,
    //         },
    //         {
    //             name: "Ethernet17",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 18,
    //         },
    //         {
    //             name: "Ethernet18",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 19,
    //         },
    //         {
    //             name: "Ethernet19",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 20,
    //         },
    //         {
    //             name: "Ethernet20",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 21,
    //         },
    //         {
    //             name: "Ethernet21",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 22,
    //         },
    //         {
    //             name: "Ethernet22",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 23,
    //         },
    //         {
    //             name: "Ethernet23",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 24,
    //         },
    //         {
    //             name: "Ethernet24",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 25,
    //         },
    //         {
    //             name: "Ethernet25",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 26,
    //         },
    //         {
    //             name: "Ethernet26",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 27,
    //         },
    //         {
    //             name: "Ethernet27",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 28,
    //         },
    //         {
    //             name: "Ethernet28",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 29,
    //         },
    //         {
    //             name: "Ethernet29",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 30,
    //         },
    //         {
    //             name: "Ethernet30",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 31,
    //         },
    //         {
    //             name: "Ethernet31",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 32,
    //         },
    //         {
    //             name: "Ethernet32",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 33,
    //         },
    //         {
    //             name: "Ethernet33",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 34,
    //         },
    //         {
    //             name: "Ethernet34",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 35,
    //         },
    //         {
    //             name: "Ethernet35",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 36,
    //         },
    //         {
    //             name: "Ethernet36",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 37,
    //         },
    //         {
    //             name: "Ethernet37",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 38,
    //         },
    //         {
    //             name: "Ethernet38",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 39,
    //         },
    //         {
    //             name: "Ethernet39",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 40,
    //         },
    //         {
    //             name: "Ethernet40",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 41,
    //         },
    //         {
    //             name: "Ethernet41",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 42,
    //         },
    //         {
    //             name: "Ethernet42",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 43,
    //         },
    //         {
    //             name: "Ethernet43",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 44,
    //         },
    //         {
    //             name: "Ethernet44",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 45,
    //         },
    //         {
    //             name: "Ethernet45",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 46,
    //         },
    //         {
    //             name: "Ethernet46",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 47,
    //         },
    //         {
    //             name: "Ethernet47",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_25GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 48,
    //         },
    //         {
    //             name: "Ethernet48",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_100GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 49,
    //         },
    //         {
    //             name: "Ethernet52",
    //             enabled: false,
    //             mtu: 9100,
    //             fec: "FEC_DISABLED",
    //             speed: "SPEED_100GB",
    //             oper_sts: "DOWN",
    //             admin_sts: "DOWN",
    //             description: "",
    //             last_chng: "2023-07-10 11:41:56+00:00 UTC",
    //             mac_addr: "0c:fc:6a:92:00:0a",
    //             id: 50,
    //         },
    //     ],
    //     function_call: true,
    // };
    // const content = [
    //     {
    //         lag_name: "PortChannel102",
    //         active: true,
    //         admin_sts: "up",
    //         mtu: 9100,
    //         name: "lacp",
    //         fallback_operational: true,
    //         oper_sts: "down",
    //         speed: "0",
    //         oper_sts_reason: "LACP_FAIL",
    //         id: 157,
    //     },
    //     {
    //         lag_name: "PortChannel101",
    //         active: true,
    //         admin_sts: "up",
    //         mtu: 9100,
    //         name: "lacp",
    //         fallback_operational: true,
    //         oper_sts: "down",
    //         speed: "0",
    //         oper_sts_reason: "ALL_LINKS_DOWN",
    //         id: 74,
    //     },
    // ];

    const gridStyle = useMemo(() => ({ height: "300px", width: "100%" }), []);

    const generateColumnDefs = (data) => {
        if (data.length > 0) {
            return Object.keys(data[0]).map((key) => ({
                headerName: key.replace(/_/g, " ").toUpperCase(),
                field: key,
                resizable: true,
                filter: true,
                sortable: true,
            }));
        }
        return [];
    };

    const isValidIPv4 = (ip) => {
        // Regular expression to match IPv4 address (0-255 in each octet)
        const ipv4Regex = /^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])$/;
        return ipv4Regex.test(ip);
    }
    
    const isValidIPv4WithCIDR = (ipWithCidr) => {
        // Regular expression to match IPv4 address (0-255 in each octet)
        const ipv4Regex = /^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])$/;
        // Regular expression to match CIDR notation (0-32)
        const cidrRegex = /^([0-9]|[12][0-9]|3[0-2])$/;
        
        // Split the input into IP address and CIDR part
        const [ip, cidr] = ipWithCidr.split('/');
        
        // Check if the IP address part is valid
        if (ipv4Regex.test(ip)) {
            // If CIDR part exists, check it
            if (cidr === undefined || cidrRegex.test(cidr)) {
                return true;
            }
        }
        return false;
    }

    console.log(isValidIPv4WithCIDR("10.2210.229.58/10"));   

    return (
        <div className="error-page-container">
            <div className="listContainer">
                <div className="listTitle">Page Not Found</div>

                {/* <SigmaGraph message={data} /> */}

                {/* <div style={gridStyle} className="ag-theme-alpine">
                    <AgGridReact
                        rowData={content}
                        columnDefs={generateColumnDefs(content)}
                    />
                </div> */}

                {/* <Chart
                    chartType={"Bar"}
                    data={data}
                    width="100%"
                    height="-webkit-fill-available"
                    legendToggle
                /> */}
            </div>
        </div>
    );
};

export default ErrorPage;
